Crear un array, llamado ar con la siguiente estructura

| 1 6 11 | 
| 2 7 12 | 
| 3 8 13 | 
| 4 9 14 | 
| 5 10 15 |

In [3]:
import numpy as np
# Crear un array con la estructura deseada
ar = np.array([[1, 6, 11],
               [2, 7, 12],
               [3, 8, 13],
               [4, 9, 14],
               [5, 10, 15]])
ar

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

Imprime. “Este array tiene X dimensiones y N elementos”. Cambiar X y N por sus valores

In [8]:
dimensiones = ar.ndim
elementos = ar.size

print(f"Este array tiene {dimensiones} dimensiones y {elementos} elementos.")


Este array tiene 2 dimensiones y 15 elementos.


Selecciona la columna 2 del array (su primer elemento es el 6)

In [11]:
ar[0,1]

6

Crea un array ar2 con los números del 15 al 54 incluidos (np.arange())

In [39]:
ar2 = np.arange(15,55)
ar2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

Divide ese ar2 en 4 filas con np.shape (reshape) y crear ar3

In [40]:
ar3 = np.reshape(ar2, (4, -1))
#ar2.shape = (4,10)
ar3

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

A partir del ar2, vuelve a crear ar2 escribiendo los valores en orden inverso

In [34]:
ar2 = np.flip(ar2)
ar2

array([54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38,
       37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15])

Crea una matriz de 5 filas y 3 columnas cuyos elementos sean números aleatorios entre 0 y 1.

In [42]:
matriz = np.random.randint(0,2,(5,3))
matriz

array([[0, 1, 0],
       [1, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 1]])