# Numpy  

Numpy es un paquete especializado en la creación, gestión y operación de arrays de una o varias dimensiones. Incluye funciones matemáticas y estádisticas básicas, así como la generación de números aleatorios.

Numpy cuenta con módulos especializados en operaciones de algebra lineal y transformaciones de Fourier entre otros. Incluso existen variedades de Numpy como Gnumpy que están diseñadas para usar la GPU para realizar cálculos.

Los tipos de datos y las arrays dmi_array Numpy son fundamentales para el resto de los componentes de Scipy, así como para otras herramientas de cómputo científico.

Por convención, cuando se manda a llamar *numpy* se hace con la abreviatura *np*


In [8]:
!pip install numpy

In [9]:
import numpy as np

## Los arrays en Numpy

Un array es una colección ordenada e indexable de objetos, todos del mismo tipo.
De manera genérica, se construyen con la siguiente sintaxis

``nombre_del_array = np.array("estructura")``

Los arrays de Numpy son estructuras que a su vez pueden contener arrays en varios niveles o "dimensiones".
Todos los arrays en una dimensión específica deben de contener el mismo número de elementos. Al número de objetos que contiene un array en cada dimensión se conoce como forma (shape).

In [10]:
# Crearemos un array de dimensión 1
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [11]:
# Crearemos un array de 2 dimensiones
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

Los arrays cuentan con el atributo *ndim*, el cual indica el número de dimensiones del array.

In [12]:
print(f"El array array_1d tiene un total de {array_1d.ndim} dimensiones, y su shape es {array_1d.shape} respectivamente, por lo cual cuenta con {array_1d.size} elementos")


El array array_1d tiene un total de 1 dimensiones, las cuales valen (3,) respectivamente, por lo cual cuenta con 3 elementos


In [13]:
print(f"El array array_1d tiene un total de {array_2d.ndim} dimensiones, y su shape es {array_2d.shape} respectivamente, por lo cual cuenta con {array_2d.size} elementos")


El array array_1d tiene un total de 2 dimensiones, las cuales valen (2, 3) respectivamente, por lo cual cuenta con 6 elementos


También podemos incluir valores nulos con *np.nan*

In [30]:
array_con_nulos = np.array([2,4,np.nan,8])
array_con_nulos

array([ 2.,  4., nan,  8.])

E incluso podemos hacer reemplazamientos de los valores nulos por algún otro valor

In [31]:
array_con_nulos[np.isnan(array_con_nulos)] = 0
array_con_nulos

array([2., 4., 0., 8.])

## Indexado de arrays

Consideremos el siguiente array:


In [33]:
mi_array = np.array([[3,4,5,9],
                       [7,8,3,12],
                       [0,3,23,20],
                       [8,11,6,21]])
mi_array

array([[ 3,  4,  5,  9],
       [ 7,  8,  3, 12],
       [ 0,  3, 23, 20],
       [ 8, 11,  6, 21]])

In [34]:
# Accesar al elemento de la fila 1 y columna 3
mi_array[0,2]

5

In [35]:
# Accesar a la fila 1 desde la segunda columna hasta la tercera
mi_array[0,1:3]

array([4, 5])

In [36]:
# Accesar a toda la fila 2
mi_array[1,:]

array([ 7,  8,  3, 12])

In [38]:
# Accesar a las filas 2 y 3
mi_array[1:3,:]

array([[ 7,  8,  3, 12],
       [ 0,  3, 23, 20]])

In [39]:
# Accesar a la columna 3
mi_array[:,2]

array([ 5,  3, 23,  6])

In [41]:
# Accesar a la última columna
mi_array[:,-1]

array([ 9, 12, 20, 21])

## Observación importante sobre los índices

Es importante saber que el indexado de arrays puede cambiar el objeto original.



In [43]:
# Consideremos la siguiente matriz
matriz = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
seleccion = matriz[1,1]
print(seleccion)
seleccion = 100
matriz

6


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
seccion = matriz[:2,]
print(seccion)


[[1 2 3 4]
 [5 6 7 8]]


In [47]:
seccion[0,0]
seccion[0,0] = 100
matriz

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

## Filtrados

Consideremos la siguiente matriz

In [48]:
matriz = np.array([[1,4],[2,4],[5,0]])
matriz

array([[1, 4],
       [2, 4],
       [5, 0]])

In [49]:
# Construir una matriz booleana que nos diga qué elementos son mayores o iguales que 2
matriz_filtrada = matriz >= 2
matriz_filtrada

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [50]:
matriz[matriz_filtrada]

array([4, 2, 4, 5])