    
# **Transformaciones**




## <font color=#003d5c>_As Type_ </font>

### Este método nos permite modificar el tipo de dato de los valores de un `array`

In [1]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[69, 66, 68, 52],
       [ 3, 82, 19, 51],
       [85,  9,  4, 58]])

In [2]:
arr_ent.astype(float)

array([[69., 66., 68., 52.],
       [ 3., 82., 19., 51.],
       [85.,  9.,  4., 58.]])

## <font color=#003d5c>_Sort_ </font>

### Este método nos permite ordenar los valores de un `array`

In [3]:
arr_ent

array([[69, 66, 68, 52],
       [ 3, 82, 19, 51],
       [85,  9,  4, 58]])

In [4]:
arr_ent.sort()
arr_ent

array([[52, 66, 68, 69],
       [ 3, 19, 51, 82],
       [ 4,  9, 58, 85]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[ 3,  9, 51, 69],
       [ 4, 19, 58, 82],
       [52, 66, 68, 85]])

## <font color=#003d5c>_Flatten_ </font>

### Este método crea un array unidimensional desde el original.

In [9]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 3  9 51]
 [69  4 19]
 [58 82 52]
 [66 68 85]]
[ 3  9 51 69  4 19 58 82 52 66 68 85]


In [12]:
rav = np.ravel(arr_ent)
print(rav)

[ 3  9 51 69  4 19 58 82 52 66 68 85]


## <font color=#003d5c>_To List_ </font>

### Este método crea una lista a partir de un array

In [14]:
lista_arr = plano_arr.tolist()
lista_arr
print(lista_arr)
type(lista_arr)

[3, 9, 51, 69, 4, 19, 58, 82, 52, 66, 68, 85]


list

## <font color=#003d5c>_Separar y juntar arrays_ </font>

In [15]:
arrays= np.split(arr_ent,4)
arrays

[array([[ 3,  9, 51]]),
 array([[69,  4, 19]]),
 array([[58, 82, 52]]),
 array([[66, 68, 85]])]

In [16]:
np.concatenate((arrays[1],arrays[0]),axis=1)

array([[69,  4, 19,  3,  9, 51]])