# Gestión de arrays

## arrays especiales

Numpy cuenta con un cierto compendio para matrices. Es importante comentar que, aunque los ejemplos siguientes son para matrices, se adaptan fácilmente indicando el shape para aplicarse a cualquier tipo de array. Además, toma en cuenta el parámetro *dtype* que nos indica que el tipo de dato a considerar, el cual, usualmente, es de tipo flotante:

``np.función(shape,dtype)``

donde 

``shape`` es una tupla donde se indica la forma del array

``dtype`` es el tipo de dato con que queremos llenarla.

In [1]:
# Matriz donde todos los elementos son iguales a 1: np.ones((u,v))
import numpy as np
ar1 = np.ones((2,1))
print(ar1)
print(ar1.dtype)

[[1.]
 [1.]]
float64


In [2]:
ar2 = np.ones((4,3),dtype = int)
print(ar2)
print(ar2.shape)
print(ar2.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(4, 3)
int64


In [3]:
# Matriz donde todos los elementos son iguales a 0: np.zeros((u,v))
ar3 = np.zeros((2,1))
print(ar3)

[[0.]
 [0.]]


In [4]:
#Generar la matriz identidad
ar4 = np.identity((4), dtype=int)
print(ar4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
# La función np.eye() permite especificar la cantidad de filas (N) y columnas (M) de la matriz, así como un índice de desplazamiento (k). Por defecto, k=0, lo que significa que la diagonal principal estará en la posición cero. Además, np.eye() acepta tanto M como N como argumentos posicionales.
ar5 = np.eye((4), dtype=float)
print(ar5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
ar6 = np.eye(4, k=2, dtype=int)
print(ar6)

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [39]:
# Matriz donde todos sus elementos son vacíos: np.empty((u,v))
np.empty((2,1),dtype = str)

array([[''],
       ['']], dtype='<U1')

In [8]:
#Esto creará un arreglo de 2 filas y 1 columna, pero sus valores serán impredecibles, ya que np.empty() simplemente asigna espacio de memoria sin inicializarlo. 
np.empty((2,1))

array([[5.43230922e-312],
       [7.29112202e-304]])

In [9]:
np.empty((4,3),dtype = bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

### La función np.linspace().

Esta función creará un array de una dimensión que contiene una secuencia lineal de números dentro de un rango dado entre un valor incial y un valor final. El número de segmentos incluyendo el valor incial y el valor final es definido meduante el parámentro num. El valor por defecto del parámetro num es de 50.

``np.linspace(inicio, fin, num=segmentos, dtype=tipo de dato)``

Donde:

* ``inicio`` corresponde al número a partir del cual comenzará la secuencia.
* ``fin`` corresponde al número en el que terminará la secuencia
* ``segmentos`` correpsonde al número de segmentos, incluyendo el valor inicial y el final que se generarán, que contendrá el array.
* ``tipo de dato`` es el tipo de dato que tendrá el array.

El valor por defecto del parámetro dtype es np.float.

In [41]:
np.linspace(0,1,num=12)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
# Usando arange para crear un array similar a linspace
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Modificación de la forma y tamaño de un array.

Estudiaremos cuatro formas básicas para manipular los tamaños de un array:

* np.ravel()
* np.reshape()
* np.resize()
* np.concatenate()

### La función np.ravel()

La función *np.ravel()* devolvera a un array de una dimensión que contiene la referencia de cada uno de los elementos del array que se ingresa como argumento.

``np.ravel(<array>)``

Donde ``<array>`` es un array de Numpy.

In [12]:
array_1 = np.array([[1, 2, 3],
                      [4, 0, -5],
                      [-6, -7, -8]])

np.ravel(array_1)

array([ 1,  2,  3,  4,  0, -5, -6, -7, -8])

In [13]:
array_1

array([[ 1,  2,  3],
       [ 4,  0, -5],
       [-6, -7, -8]])

### La función np.reshape().

La función *np.reshape()* regresará un array compuesto por el mismo número de elementos que el array ingresado como primer argumento, pero con la forma descrita por el objeto de tipo tuple que se ingrese como segundo argumento. Las nuevas dimensiones deben de coincidir con el numero total de elementos del array de origen.

``np.reshape(<array>, <forma>)``

Donde:

* ``<array>`` es un array de Numpy.
* ``<forma>`` es un un objeto de tipo tuple que describe la forma del array resultante.

In [42]:
array_2 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

array_2.shape

(3, 4)

In [45]:
np.reshape(array_2,(6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [16]:
np.reshape(array_2,(3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### La función np.resize()

La función *np.resize()* devolvera un nuevo array a partir del array que se ingrese como primer argumento, con la forma que se ingrese como segundo argumento.

En caso de que las nuevas dimensiones sean menores a tamaño original, se recortarán los últimos de ellos.

En caso de que las nuevas dimensiones sean mayores al tamaño original, los elementos faltantes serán sustituidos por una secuencia iterativa de los elementos contenidos en el array.

``np.resize(<array>, <forma>)``

Donde:

* ``<array>`` es un array de Numpy.
* ``<forma>`` es un objeto de tipo tuple que describe la nueva forma del array resultante.

In [17]:
array_3 = np.array([[1, 2],
                     [3, 4]])

In [18]:
np.resize(array_3, (4, 2))


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### La función np.concatenate().

Une una secuencia de arrays contenidos dentro de un objeto tuple a un eje existente, se puede indicar el eje en el que se realizará la operación ingresando su número correspondiente como tercer argumento.

``np.concatenate(<array 1>, <array 2>, <eje>)``

Donde 

* ``eje = 0`` significa pegar array 2 debajo de array 1
* ``eje = 1`` significa pegar array 2 a la derecha de array 1


In [19]:
array_1 = np.array([[1, 2],
                      [3, 4]])
array_2 = np.array([[5, 6],
                      [7, 8]])

In [20]:
np.concatenate((array_1, array_2), 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
np.concatenate((array_1, array_2), 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Matrices con elementos aleatorios

### El paquete np.random.

#### La función np.random.rand().

La función *np.random.rand()* crea un array cuyos elementos son valores aleatorios que van de 0 a antes de 1 dentro de una distribución uniforme.

``np.random.rand(<forma>)``

Donde ``forma`` es una secuencia de valores enteros separados por comas que definen la forma del array.



In [22]:
#La siguiente celda generará un array de forma (2, 2, 2)conteniendo números aleatorios.
np.random.rand(3,5)

array([[0.65638457, 0.87479094, 0.40958367, 0.48045165, 0.50675328],
       [0.16792765, 0.23505256, 0.1508841 , 0.75229939, 0.10409239],
       [0.94127322, 0.37053369, 0.96040084, 0.04238701, 0.36688086]])

#### La función np.random.randint().

La función *np.random.randint()* crea un array cuyos elementos son valores entros aleatorios en un rango dado.

``np.random.randint(<inicio>, <fin>, <forma>)``

Donde:

``<inicio>`` es el valor inicial del rango a partir del cual se generarán los números aleatorios, incluyéndolo a este.

``<fin>`` es el valor final del rango a partir del cual se generarán los números aleatorios, sin incluirlo.

``<forma>`` es un objeto tuple que definen la forma del array.

In [23]:
# La siguente celda creará una array de forma (3, 3) con valores enteros que pueden ir de 1 a 2.
np.random.randint(1, 3, (3, 3))

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [24]:
# La siguente celda creará una array de forma (3, 2, 4) con valores enteros que pueden ir de 0 a 255.
np.random.randint(0, 256, (10, 3))

array([[  0, 254,  27],
       [219, 148, 192],
       [235,  63, 175],
       [ 60, 244, 231],
       [139, 238, 222],
       [137, 121,  32],
       [ 91, 231, 155],
       [ 61, 236, 232],
       [126, 151,   4],
       [220,  96,  33]])

## Álgebra lineal
    
El componente más poderoso de Numpy es su capacidad de realizar operaciones con arrays, y un caso particular de ellos son las matrices numéricas.    

### Producto puntual (de Hadamard) de dos matrices.

Es el producto "elemento a elemento" de dos matrices. Ambas deben ser del mismo tamaño.


In [25]:
# matriz1 * matriz2
np.array([[1,2,3],[4,5,6]]) * np.array([[0,1,0],[0,0,1]])

array([[0, 2, 0],
       [0, 0, 6]])

In [26]:
A = np.array([[1,4,3],[2,5,1]])

(A >= 3 ) * A

array([[0, 4, 3],
       [0, 5, 0]])

### Producto usual/escalar de matrices

Es el producto usual de matrices. Se debe tomar en cuenta que si $A$ y $B$ son dos matrices, para que el producto $AB$ tenga sentido se debe cumplir que el número de columnas de $A$ es igual al número de filas de $B$. Se obtiene como resultado una matriz con el mismo número de filas que $A$ y el mismo número de columnas de $B$

In [27]:
a = np.array([1,2,3], float)
b = np.array([0,1,1], float)
#Producto escalar
np.dot(a,b)
a.dot(b)

#Producto escalar = (1*0) + (2*1) + (3*1) = 0 + 2 + 3 = 5


5.0

In [28]:
A = np.array([[1,4,3],[2,5,1]])
B = np.array([[2,3,1,0],[5,5,1,0],[4,1,2,0]])

A @ B

array([[34, 26, 11,  0],
       [33, 32,  9,  0]])

C[0][0] = (1*2) + (4*5) + (3*4) = 2 + 20 + 12 = 34
C[0][1] = (1*3) + (4*5) + (3*1) = 3 + 20 + 3 = 26
C[0][2] = (1*1) + (4*1) + (3*2) = 1 + 4 + 6 = 11
C[0][3] = (1*0) + (4*0) + (3*0) = 0 + 0 + 0 = 0

C[1][0] = (2*2) + (5*5) + (1*4) = 4 + 25 + 4 = 33
C[1][1] = (2*3) + (5*5) + (1*1) = 6 + 25 + 1 = 32
C[1][2] = (2*1) + (5*1) + (1*2) = 2 + 5 + 2 = 9
C[1][3] = (2*0) + (5*0) + (1*0) = 0 + 0 + 0 = 0

In [29]:
print(f"La forma de A es {A.shape}; la de B es {B.shape}. Por lo tanto la de AB es {(A @ B).shape}")

La forma de A es (2, 3); la de B es (3, 4). Por lo tanto la de AB es (2, 4)


### El paquete numpy.linalg

La biblioteca especializada en operaciones de algebra lineal de Numpy es numpy.linalg.

Algunas de las funciones mas importantes que contiene son

* np.linalg.det()
* np.linalg.solve()
* np.linalg.inv()

#### Determinantes

Considere la matriz $$\left(\begin{array}{ccc}0&1&2\\3&4&5\\6&7&8\end{array}\right)$$

In [30]:
# El cálculo de su determinante es
A = np.arange(9).reshape(3,3)

# det(matriz)=a11 * (a22 * a33 − a23 * a32)− a12 ⋅(a21 * a33 − a23 * a31) + a13 * (a21 * a32 − a22 * a31)

np.linalg.det(A)

0.0

### Soluciones de ecuaciones lineales con la función ```np.linalg.solve()```.

Un sistema de ecuaciones lineales coresponde un conjunto de ecuaciones de la forma:

$$
a_{11}x_1 + a_{12}x_2 + \cdots a_{1n}x_n = y_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots a_{2n}x_n = y_2\\
\vdots\\
a_{m1}x_1 + a_{m2}x_2 + \cdots a_{mn}x_n = y_m
$$

Lo cual puede ser expresado de forma matricial.

$$ 
\begin{bmatrix}a_{11}\\a_{21}\\ \vdots\\ a_{m1}\end{bmatrix}x_1 + \begin{bmatrix}a_{12}\\a_{22}\\ \vdots\\ a_{m2}\end{bmatrix}x_2 + \cdots \begin{bmatrix}a_{m1}\\a_{m2}\\ \vdots\\ a_{mn}\end{bmatrix}x_n = \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{m}\end{bmatrix}
$$

Existen múltiples métodos para calcular los valores $x_1, x_2 \cdots x_n$ que cumplan con el sistema siempre que $m = n$.

Numpy cuenta con la función *np.linalg.solve()*, la cual puede calcular la solución de un sistema de ecuaciones lineales al expresarse como un par de matrices de la siguiente foma:

$$ 
\begin{bmatrix}a_{11}&a_{12}&\cdots&a_{1n}\\a_{21}&a_{22}&\cdots&a_{2n}\\ \vdots\\ a_{n1}&a_{n2}&\cdots&a_{nn}\end{bmatrix}= \begin{bmatrix}y_{1}\\y_{2}\\ \vdots\\ y_{n}\end{bmatrix}
$$

La función ```numpy.linagl.solve()``` permite resolver sistemas de ecuaciones lineales ingresando un array de dimensiones ```(n, n)``` como primer argumente y otro con dimensión ```(n)``` como segundo argumento. 

**Ejemplo:**

* Para resolver el sistema de ecuaciones:

$$
2x_1 + 5x_2 - 3x_3 = 22.2 \\
11x_1 - 4x_2 + 22x_3 = 11.6 \\
54x_1 + 1x_2 + 19x_3 = -40.1 \\
$$

* Se realiza lo siguiente:

In [31]:
a = np.array([[2, 5, -3],
              [11, -4, 22],
              [54, 1, 19]])

y = np.array([22.2, 11.6, -40.1])

np.linalg.solve(a, y)

array([-1.80243902,  6.7549776 ,  2.65666999])

## Matriz inversa.

In [32]:
np.linalg.inv(a)

array([[-0.02439024, -0.02439024,  0.02439024],
       [ 0.24365356,  0.04977601, -0.01916376],
       [ 0.05649577,  0.06669985, -0.01567944]])

In [33]:
np.linalg.inv(a).dot(y)

array([-1.80243902,  6.7549776 ,  2.65666999])

## Transpuesta de una matriz

In [34]:
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
b.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [36]:
np.transpose(b)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])