    
# **Transformaciones**




## <font color=#003d5c>_As Type_ </font>

### Este método nos permite modificar el tipo de dato de los valores de un `array`

In [1]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[79,  1,  3, 74],
       [88, 23, 16, 88],
       [26, 46, 79, 35]])

In [2]:
arr_ent.astype(float)

array([[79.,  1.,  3., 74.],
       [88., 23., 16., 88.],
       [26., 46., 79., 35.]])

## <font color=#003d5c>_Sort_ </font>

### Este método nos permite ordenar los valores de un `array`

In [3]:
arr_ent

array([[79,  1,  3, 74],
       [88, 23, 16, 88],
       [26, 46, 79, 35]])

In [4]:
arr_ent.sort()
arr_ent

array([[ 1,  3, 74, 79],
       [16, 23, 88, 88],
       [26, 35, 46, 79]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[ 1,  3, 46, 79],
       [16, 23, 74, 79],
       [26, 35, 88, 88]])

## <font color=#003d5c>_Reshape_ </font>

### Este método nos permite modificar las dimensiones de un `array`.

In [6]:
arr_ent

array([[ 1,  3, 46, 79],
       [16, 23, 74, 79],
       [26, 35, 88, 88]])

In [7]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 1,  3, 46],
       [79, 16, 23],
       [74, 79, 26],
       [35, 88, 88]])

## <font color=#003d5c>_Flatten_ </font>

### Este método crea un array unidimensional desde el original.

In [8]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 1  3 46]
 [79 16 23]
 [74 79 26]
 [35 88 88]]
[ 1  3 46 79 16 23 74 79 26 35 88 88]


## <font color=#003d5c>_To List_ </font>

### Este método crea una lista a partir de un array

In [9]:
lista_arr = plano_arr.tolist()
lista_arr
type(lista_arr)

list

## <font color=#003d5c>_Separar y juntar arrays_ </font>

In [10]:
arrays= np.split(arr_ent,4)
arrays

[array([[ 1,  3, 46]]),
 array([[79, 16, 23]]),
 array([[74, 79, 26]]),
 array([[35, 88, 88]])]

In [11]:
np.concatenate((arrays[1],arrays[0]),axis=1)

array([[79, 16, 23,  1,  3, 46]])

## <font color=#003d5c>_La matriz transpuesta_ </font>

In [12]:
arr_ent

array([[ 1,  3, 46],
       [79, 16, 23],
       [74, 79, 26],
       [35, 88, 88]])

In [13]:
t_arr = arr_ent.T
t_arr

array([[ 1, 79, 74, 35],
       [ 3, 16, 79, 88],
       [46, 23, 26, 88]])